/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.CreditCard;

import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * User Credit Card
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "credit_card", schema = "vvv")
public class CreditCardRecord extends UpdatableRecordImpl<CreditCardRecord> implements Record6<Integer, Integer, Integer, String, Date, Integer> {

	private static final long serialVersionUID = -2095941517;

	/**
	 * Setter for <code>vvv.credit_card.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.credit_card.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.user_id</code>.
	 */
	@Column(name = "user_id", nullable = false, precision = 10)
	public Integer getUserId() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vvv.credit_card.number</code>.
	 */
	public void setNumber(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.number</code>.
	 */
	@Column(name = "number", nullable = false, precision = 10)
	public Integer getNumber() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>vvv.credit_card.holder_name</code>.
	 */
	public void setHolderName(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.holder_name</code>.
	 */
	@Column(name = "holder_name", nullable = false, length = 255)
	public String getHolderName() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>vvv.credit_card.expire</code>.
	 */
	public void setExpire(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.expire</code>.
	 */
	@Column(name = "expire", nullable = false)
	public Date getExpire() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>vvv.credit_card.facture_address_id</code>.
	 */
	public void setFactureAddressId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.facture_address_id</code>.
	 */
	@Column(name = "facture_address_id", nullable = false, precision = 10)
	public Integer getFactureAddressId() {
		return (Integer) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, String, Date, Integer> fieldsRow() {
		return (Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row6<Integer, Integer, Integer, String, Date, Integer> valuesRow() {
		return (Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CreditCard.CREDIT_CARD.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CreditCard.CREDIT_CARD.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return CreditCard.CREDIT_CARD.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return CreditCard.CREDIT_CARD.HOLDER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return CreditCard.CREDIT_CARD.EXPIRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return CreditCard.CREDIT_CARD.FACTURE_ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getHolderName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getExpire();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getFactureAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value2(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value3(Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value4(String value) {
		setHolderName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value5(Date value) {
		setExpire(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value6(Integer value) {
		setFactureAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord values(Integer value1, Integer value2, Integer value3, String value4, Date value5, Integer value6) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CreditCardRecord
	 */
	public CreditCardRecord() {
		super(CreditCard.CREDIT_CARD);
	}

	/**
	 * Create a detached, initialised CreditCardRecord
	 */
	public CreditCardRecord(Integer id, Integer userId, Integer number, String holderName, Date expire, Integer factureAddressId) {
		super(CreditCard.CREDIT_CARD);

		setValue(0, id);
		setValue(1, userId);
		setValue(2, number);
		setValue(3, holderName);
		setValue(4, expire);
		setValue(5, factureAddressId);
	}
}
