/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.CreditCard;

import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "credit_card", schema = "vvv")
public class CreditCardRecord extends UpdatableRecordImpl<CreditCardRecord> implements Record5<Integer, Integer, String, Date, Integer> {

	private static final long serialVersionUID = -1423354458;

	/**
	 * Setter for <code>vvv.credit_card.user_id</code>.
	 */
	public void setUserId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.user_id</code>.
	 */
	@Id
	@Column(name = "user_id", unique = true, nullable = false, precision = 10)
	public Integer getUserId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.credit_card.number</code>.
	 */
	public void setNumber(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.number</code>.
	 */
	@Column(name = "number", nullable = false, precision = 10)
	public Integer getNumber() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vvv.credit_card.holder_name</code>.
	 */
	public void setHolderName(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.holder_name</code>.
	 */
	@Column(name = "holder_name", nullable = false, length = 255)
	public String getHolderName() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>vvv.credit_card.expire</code>.
	 */
	public void setExpire(Date value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.expire</code>.
	 */
	@Column(name = "expire", nullable = false)
	public Date getExpire() {
		return (Date) getValue(3);
	}

	/**
	 * Setter for <code>vvv.credit_card.address_id</code>.
	 */
	public void setAddressId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vvv.credit_card.address_id</code>.
	 */
	@Column(name = "address_id", precision = 10)
	public Integer getAddressId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Date, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Date, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return CreditCard.CREDIT_CARD.USER_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return CreditCard.CREDIT_CARD.NUMBER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return CreditCard.CREDIT_CARD.HOLDER_NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field4() {
		return CreditCard.CREDIT_CARD.EXPIRE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return CreditCard.CREDIT_CARD.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getUserId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getNumber();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getHolderName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value4() {
		return getExpire();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value1(Integer value) {
		setUserId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value2(Integer value) {
		setNumber(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value3(String value) {
		setHolderName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value4(Date value) {
		setExpire(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord value5(Integer value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public CreditCardRecord values(Integer value1, Integer value2, String value3, Date value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached CreditCardRecord
	 */
	public CreditCardRecord() {
		super(CreditCard.CREDIT_CARD);
	}

	/**
	 * Create a detached, initialised CreditCardRecord
	 */
	public CreditCardRecord(Integer userId, Integer number, String holderName, Date expire, Integer addressId) {
		super(CreditCard.CREDIT_CARD);

		setValue(0, userId);
		setValue(1, number);
		setValue(2, holderName);
		setValue(3, expire);
		setValue(4, addressId);
	}
}
