/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.Itinerary;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "itinerary", schema = "vvv", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"reservation_id", "viagem_id"})
})
public class ItineraryRecord extends UpdatableRecordImpl<ItineraryRecord> implements Record2<Integer, Integer> {

	private static final long serialVersionUID = 636461711;

	/**
	 * Setter for <code>vvv.itinerary.reservation_id</code>.
	 */
	public void setReservationId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.itinerary.reservation_id</code>.
	 */
	@Column(name = "reservation_id", nullable = false, precision = 10)
	public Integer getReservationId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.itinerary.viagem_id</code>.
	 */
	public void setViagemId(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.itinerary.viagem_id</code>.
	 */
	@Column(name = "viagem_id", nullable = false, precision = 10)
	public Integer getViagemId() {
		return (Integer) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record2<Integer, Integer> key() {
		return (Record2) super.key();
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> fieldsRow() {
		return (Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row2<Integer, Integer> valuesRow() {
		return (Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Itinerary.ITINERARY.RESERVATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Itinerary.ITINERARY.VIAGEM_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getReservationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getViagemId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItineraryRecord value1(Integer value) {
		setReservationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItineraryRecord value2(Integer value) {
		setViagemId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItineraryRecord values(Integer value1, Integer value2) {
		value1(value1);
		value2(value2);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ItineraryRecord
	 */
	public ItineraryRecord() {
		super(Itinerary.ITINERARY);
	}

	/**
	 * Create a detached, initialised ItineraryRecord
	 */
	public ItineraryRecord(Integer reservationId, Integer viagemId) {
		super(Itinerary.ITINERARY);

		setValue(0, reservationId);
		setValue(1, viagemId);
	}
}
