/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.Modal;

import java.sql.Date;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "modal", schema = "vvv")
public class ModalRecord extends UpdatableRecordImpl<ModalRecord> implements Record8<Integer, Integer, Integer, String, Date, Date, Date, Integer> {

	private static final long serialVersionUID = 1976456916;

	/**
	 * Setter for <code>vvv.modal.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.modal.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.modal.type</code>.
	 */
	public void setType(Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.modal.type</code>.
	 */
	@Column(name = "type", nullable = false, precision = 10)
	public Integer getType() {
		return (Integer) getValue(1);
	}

	/**
	 * Setter for <code>vvv.modal.capacity</code>.
	 */
	public void setCapacity(Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vvv.modal.capacity</code>.
	 */
	@Column(name = "capacity", nullable = false, precision = 10)
	public Integer getCapacity() {
		return (Integer) getValue(2);
	}

	/**
	 * Setter for <code>vvv.modal.model</code>.
	 */
	public void setModel(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vvv.modal.model</code>.
	 */
	@Column(name = "model", nullable = false, length = 255)
	public String getModel() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>vvv.modal.manufacture</code>.
	 */
	public void setManufacture(Date value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vvv.modal.manufacture</code>.
	 */
	@Column(name = "manufacture", nullable = false)
	public Date getManufacture() {
		return (Date) getValue(4);
	}

	/**
	 * Setter for <code>vvv.modal.maintenance_start</code>.
	 */
	public void setMaintenanceStart(Date value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vvv.modal.maintenance_start</code>.
	 */
	@Column(name = "maintenance_start", nullable = false)
	public Date getMaintenanceStart() {
		return (Date) getValue(5);
	}

	/**
	 * Setter for <code>vvv.modal.maintenance_end</code>.
	 */
	public void setMaintenanceEnd(Date value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>vvv.modal.maintenance_end</code>.
	 */
	@Column(name = "maintenance_end", nullable = false)
	public Date getMaintenanceEnd() {
		return (Date) getValue(6);
	}

	/**
	 * Setter for <code>vvv.modal.carriers_id</code>.
	 */
	public void setCarriersId(Integer value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>vvv.modal.carriers_id</code>.
	 */
	@Column(name = "carriers_id", nullable = false, precision = 10)
	public Integer getCarriersId() {
		return (Integer) getValue(7);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, String, Date, Date, Date, Integer> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, Integer, String, Date, Date, Date, Integer> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Modal.MODAL.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Modal.MODAL.TYPE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field3() {
		return Modal.MODAL.CAPACITY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Modal.MODAL.MODEL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field5() {
		return Modal.MODAL.MANUFACTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field6() {
		return Modal.MODAL.MAINTENANCE_START;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Date> field7() {
		return Modal.MODAL.MAINTENANCE_END;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field8() {
		return Modal.MODAL.CARRIERS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value3() {
		return getCapacity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getModel();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value5() {
		return getManufacture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value6() {
		return getMaintenanceStart();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Date value7() {
		return getMaintenanceEnd();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value8() {
		return getCarriersId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value2(Integer value) {
		setType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value3(Integer value) {
		setCapacity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value4(String value) {
		setModel(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value5(Date value) {
		setManufacture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value6(Date value) {
		setMaintenanceStart(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value7(Date value) {
		setMaintenanceEnd(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord value8(Integer value) {
		setCarriersId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ModalRecord values(Integer value1, Integer value2, Integer value3, String value4, Date value5, Date value6, Date value7, Integer value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ModalRecord
	 */
	public ModalRecord() {
		super(Modal.MODAL);
	}

	/**
	 * Create a detached, initialised ModalRecord
	 */
	public ModalRecord(Integer id, Integer type, Integer capacity, String model, Date manufacture, Date maintenanceStart, Date maintenanceEnd, Integer carriersId) {
		super(Modal.MODAL);

		setValue(0, id);
		setValue(1, type);
		setValue(2, capacity);
		setValue(3, model);
		setValue(4, manufacture);
		setValue(5, maintenanceStart);
		setValue(6, maintenanceEnd);
		setValue(7, carriersId);
	}
}
