/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.RetailOutlet;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "retail_outlet", schema = "vvv")
public class RetailOutletRecord extends UpdatableRecordImpl<RetailOutletRecord> implements Record5<Integer, String, String, String, Integer> {

	private static final long serialVersionUID = -1114063213;

	/**
	 * Setter for <code>vvv.retail_outlet.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.retail_outlet.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.retail_outlet.name</code>.
	 */
	public void setName(String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.retail_outlet.name</code>.
	 */
	@Column(name = "name", nullable = false, length = 255)
	public String getName() {
		return (String) getValue(1);
	}

	/**
	 * Setter for <code>vvv.retail_outlet.cnpj</code>.
	 */
	public void setCnpj(String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vvv.retail_outlet.cnpj</code>.
	 */
	@Column(name = "cnpj", length = 14)
	public String getCnpj() {
		return (String) getValue(2);
	}

	/**
	 * Setter for <code>vvv.retail_outlet.phone</code>.
	 */
	public void setPhone(String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vvv.retail_outlet.phone</code>.
	 */
	@Column(name = "phone", length = 50)
	public String getPhone() {
		return (String) getValue(3);
	}

	/**
	 * Setter for <code>vvv.retail_outlet.address_id</code>.
	 */
	public void setAddressId(Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vvv.retail_outlet.address_id</code>.
	 */
	@Column(name = "address_id", nullable = false, precision = 10)
	public Integer getAddressId() {
		return (Integer) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Integer> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, String, String, String, Integer> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return RetailOutlet.RETAIL_OUTLET.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field2() {
		return RetailOutlet.RETAIL_OUTLET.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return RetailOutlet.RETAIL_OUTLET.CNPJ;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return RetailOutlet.RETAIL_OUTLET.PHONE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field5() {
		return RetailOutlet.RETAIL_OUTLET.ADDRESS_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getCnpj();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getPhone();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value5() {
		return getAddressId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord value2(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord value3(String value) {
		setCnpj(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord value4(String value) {
		setPhone(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord value5(Integer value) {
		setAddressId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutletRecord values(Integer value1, String value2, String value3, String value4, Integer value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RetailOutletRecord
	 */
	public RetailOutletRecord() {
		super(RetailOutlet.RETAIL_OUTLET);
	}

	/**
	 * Create a detached, initialised RetailOutletRecord
	 */
	public RetailOutletRecord(Integer id, String name, String cnpj, String phone, Integer addressId) {
		super(RetailOutlet.RETAIL_OUTLET);

		setValue(0, id);
		setValue(1, name);
		setValue(2, cnpj);
		setValue(3, phone);
		setValue(4, addressId);
	}
}
