/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.records;


import Rest.Model.tables.Route;

import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "route", schema = "vvv")
public class RouteRecord extends UpdatableRecordImpl<RouteRecord> implements Record7<Integer, Timestamp, Timestamp, Integer, Double, Integer, Integer> {

	private static final long serialVersionUID = 1152132723;

	/**
	 * Setter for <code>vvv.route.id</code>.
	 */
	public void setId(Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>vvv.route.id</code>.
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return (Integer) getValue(0);
	}

	/**
	 * Setter for <code>vvv.route.departure</code>.
	 */
	public void setDeparture(Timestamp value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>vvv.route.departure</code>.
	 */
	@Column(name = "departure", nullable = false)
	public Timestamp getDeparture() {
		return (Timestamp) getValue(1);
	}

	/**
	 * Setter for <code>vvv.route.arrival</code>.
	 */
	public void setArrival(Timestamp value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>vvv.route.arrival</code>.
	 */
	@Column(name = "arrival", nullable = false)
	public Timestamp getArrival() {
		return (Timestamp) getValue(2);
	}

	/**
	 * Setter for <code>vvv.route.modal_id</code>.
	 */
	public void setModalId(Integer value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>vvv.route.modal_id</code>.
	 */
	@Column(name = "modal_id", nullable = false, precision = 10)
	public Integer getModalId() {
		return (Integer) getValue(3);
	}

	/**
	 * Setter for <code>vvv.route.value</code>.
	 */
	public void setValue(Double value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>vvv.route.value</code>.
	 */
	@Column(name = "value", nullable = false, precision = 12)
	public Double getValue() {
		return (Double) getValue(4);
	}

	/**
	 * Setter for <code>vvv.route.origin_id</code>.
	 */
	public void setOriginId(Integer value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>vvv.route.origin_id</code>.
	 */
	@Column(name = "origin_id", nullable = false, precision = 10)
	public Integer getOriginId() {
		return (Integer) getValue(5);
	}

	/**
	 * Setter for <code>vvv.route.destination_id</code>.
	 */
	public void setDestinationId(Integer value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>vvv.route.destination_id</code>.
	 */
	@Column(name = "destination_id", nullable = false, precision = 10)
	public Integer getDestinationId() {
		return (Integer) getValue(6);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record7 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Timestamp, Timestamp, Integer, Double, Integer, Integer> fieldsRow() {
		return (Row7) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row7<Integer, Timestamp, Timestamp, Integer, Double, Integer, Integer> valuesRow() {
		return (Row7) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Route.ROUTE.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field2() {
		return Route.ROUTE.DEPARTURE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field3() {
		return Route.ROUTE.ARRIVAL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field4() {
		return Route.ROUTE.MODAL_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Double> field5() {
		return Route.ROUTE.VALUE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field6() {
		return Route.ROUTE.ORIGIN_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field7() {
		return Route.ROUTE.DESTINATION_ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value2() {
		return getDeparture();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value3() {
		return getArrival();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value4() {
		return getModalId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Double value5() {
		return getValue();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value6() {
		return getOriginId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value7() {
		return getDestinationId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value2(Timestamp value) {
		setDeparture(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value3(Timestamp value) {
		setArrival(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value4(Integer value) {
		setModalId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value5(Double value) {
		setValue(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value6(Integer value) {
		setOriginId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord value7(Integer value) {
		setDestinationId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RouteRecord values(Integer value1, Timestamp value2, Timestamp value3, Integer value4, Double value5, Integer value6, Integer value7) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached RouteRecord
	 */
	public RouteRecord() {
		super(Route.ROUTE);
	}

	/**
	 * Create a detached, initialised RouteRecord
	 */
	public RouteRecord(Integer id, Timestamp departure, Timestamp arrival, Integer modalId, Double value, Integer originId, Integer destinationId) {
		super(Route.ROUTE);

		setValue(0, id);
		setValue(1, departure);
		setValue(2, arrival);
		setValue(3, modalId);
		setValue(4, value);
		setValue(5, originId);
		setValue(6, destinationId);
	}
}
