/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.CarrierRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Carrier extends TableImpl<CarrierRecord> {

	private static final long serialVersionUID = 321163884;

	/**
	 * The reference instance of <code>vvv.carrier</code>
	 */
	public static final Carrier CARRIER = new Carrier();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<CarrierRecord> getRecordType() {
		return CarrierRecord.class;
	}

	/**
	 * The column <code>vvv.carrier.id</code>.
	 */
	public final TableField<CarrierRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.carrier.name</code>.
	 */
	public final TableField<CarrierRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>vvv.carrier.url</code>.
	 */
	public final TableField<CarrierRecord, String> URL = createField("url", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

	/**
	 * Create a <code>vvv.carrier</code> table reference
	 */
	public Carrier() {
		this("carrier", null);
	}

	/**
	 * Create an aliased <code>vvv.carrier</code> table reference
	 */
	public Carrier(String alias) {
		this(alias, CARRIER);
	}

	private Carrier(String alias, Table<CarrierRecord> aliased) {
		this(alias, aliased, null);
	}

	private Carrier(String alias, Table<CarrierRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<CarrierRecord> getPrimaryKey() {
		return Keys.KEY_CARRIER_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<CarrierRecord>> getKeys() {
		return Arrays.<UniqueKey<CarrierRecord>>asList(Keys.KEY_CARRIER_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Carrier as(String alias) {
		return new Carrier(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Carrier rename(String name) {
		return new Carrier(name, null);
	}
}
