/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.EmployeeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Employee extends TableImpl<EmployeeRecord> {

	private static final long serialVersionUID = -1148016401;

	/**
	 * The reference instance of <code>vvv.employee</code>
	 */
	public static final Employee EMPLOYEE = new Employee();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<EmployeeRecord> getRecordType() {
		return EmployeeRecord.class;
	}

	/**
	 * The column <code>vvv.employee.user_id</code>.
	 */
	public final TableField<EmployeeRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.employee.cpf</code>.
	 */
	public final TableField<EmployeeRecord, String> CPF = createField("cpf", org.jooq.impl.SQLDataType.VARCHAR.length(11).nullable(false), this, "");

	/**
	 * The column <code>vvv.employee.phone</code>.
	 */
	public final TableField<EmployeeRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>vvv.employee.address_id</code>.
	 */
	public final TableField<EmployeeRecord, Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.employee.post</code>.
	 */
	public final TableField<EmployeeRecord, Byte> POST = createField("post", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>vvv.employee.work_days</code>.
	 */
	public final TableField<EmployeeRecord, byte[]> WORK_DAYS = createField("work_days", org.jooq.impl.SQLDataType.BINARY.length(7), this, "");

	/**
	 * Create a <code>vvv.employee</code> table reference
	 */
	public Employee() {
		this("employee", null);
	}

	/**
	 * Create an aliased <code>vvv.employee</code> table reference
	 */
	public Employee(String alias) {
		this(alias, EMPLOYEE);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased) {
		this(alias, aliased, null);
	}

	private Employee(String alias, Table<EmployeeRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<EmployeeRecord> getPrimaryKey() {
		return Keys.KEY_EMPLOYEE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<EmployeeRecord>> getKeys() {
		return Arrays.<UniqueKey<EmployeeRecord>>asList(Keys.KEY_EMPLOYEE_PRIMARY, Keys.KEY_EMPLOYEE_CPF_UNIQUE, Keys.KEY_EMPLOYEE_ADDRESS_ID_UNIQUE);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<EmployeeRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<EmployeeRecord, ?>>asList(Keys.FK_EMPLOYEE_USER1, Keys.FK_EMPLOYEE_ADDRESS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Employee as(String alias) {
		return new Employee(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Employee rename(String name) {
		return new Employee(name, null);
	}
}
