/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.ItineraryRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Itinerary extends TableImpl<ItineraryRecord> {

	private static final long serialVersionUID = -1337375109;

	/**
	 * The reference instance of <code>vvv.itinerary</code>
	 */
	public static final Itinerary ITINERARY = new Itinerary();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ItineraryRecord> getRecordType() {
		return ItineraryRecord.class;
	}

	/**
	 * The column <code>vvv.itinerary.reservation_id</code>.
	 */
	public final TableField<ItineraryRecord, Integer> RESERVATION_ID = createField("reservation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.itinerary.viagem_id</code>.
	 */
	public final TableField<ItineraryRecord, Integer> VIAGEM_ID = createField("viagem_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>vvv.itinerary</code> table reference
	 */
	public Itinerary() {
		this("itinerary", null);
	}

	/**
	 * Create an aliased <code>vvv.itinerary</code> table reference
	 */
	public Itinerary(String alias) {
		this(alias, ITINERARY);
	}

	private Itinerary(String alias, Table<ItineraryRecord> aliased) {
		this(alias, aliased, null);
	}

	private Itinerary(String alias, Table<ItineraryRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ItineraryRecord> getPrimaryKey() {
		return Keys.KEY_ITINERARY_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ItineraryRecord>> getKeys() {
		return Arrays.<UniqueKey<ItineraryRecord>>asList(Keys.KEY_ITINERARY_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ItineraryRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ItineraryRecord, ?>>asList(Keys.FK_RESERVATION_HAS_VIAGEM_RESERVATION1, Keys.FK_RESERVATION_HAS_VIAGEM_VIAGEM1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Itinerary as(String alias) {
		return new Itinerary(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Itinerary rename(String name) {
		return new Itinerary(name, null);
	}
}
