/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.ModalRecord;

import java.sql.Date;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Modal extends TableImpl<ModalRecord> {

	private static final long serialVersionUID = 1962099671;

	/**
	 * The reference instance of <code>vvv.modal</code>
	 */
	public static final Modal MODAL = new Modal();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ModalRecord> getRecordType() {
		return ModalRecord.class;
	}

	/**
	 * The column <code>vvv.modal.id</code>.
	 */
	public final TableField<ModalRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.type</code>.
	 */
	public final TableField<ModalRecord, Integer> TYPE = createField("type", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.capacity</code>.
	 */
	public final TableField<ModalRecord, Integer> CAPACITY = createField("capacity", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.model</code>.
	 */
	public final TableField<ModalRecord, String> MODEL = createField("model", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.manufacture</code>.
	 */
	public final TableField<ModalRecord, Date> MANUFACTURE = createField("manufacture", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.maintenance_start</code>.
	 */
	public final TableField<ModalRecord, Date> MAINTENANCE_START = createField("maintenance_start", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.maintenance_end</code>.
	 */
	public final TableField<ModalRecord, Date> MAINTENANCE_END = createField("maintenance_end", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

	/**
	 * The column <code>vvv.modal.carriers_id</code>.
	 */
	public final TableField<ModalRecord, Integer> CARRIERS_ID = createField("carriers_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>vvv.modal</code> table reference
	 */
	public Modal() {
		this("modal", null);
	}

	/**
	 * Create an aliased <code>vvv.modal</code> table reference
	 */
	public Modal(String alias) {
		this(alias, MODAL);
	}

	private Modal(String alias, Table<ModalRecord> aliased) {
		this(alias, aliased, null);
	}

	private Modal(String alias, Table<ModalRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ModalRecord> getPrimaryKey() {
		return Keys.KEY_MODAL_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ModalRecord>> getKeys() {
		return Arrays.<UniqueKey<ModalRecord>>asList(Keys.KEY_MODAL_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ModalRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ModalRecord, ?>>asList(Keys.FK_MODAL_CARRIERS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Modal as(String alias) {
		return new Modal(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Modal rename(String name) {
		return new Modal(name, null);
	}
}
