/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.ReservationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Reservation extends TableImpl<ReservationRecord> {

	private static final long serialVersionUID = -571947212;

	/**
	 * The reference instance of <code>vvv.reservation</code>
	 */
	public static final Reservation RESERVATION = new Reservation();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<ReservationRecord> getRecordType() {
		return ReservationRecord.class;
	}

	/**
	 * The column <code>vvv.reservation.id</code>.
	 */
	public final TableField<ReservationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.reservation.date</code>.
	 */
	public final TableField<ReservationRecord, Timestamp> DATE = createField("date", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>vvv.reservation.status</code>.
	 */
	public final TableField<ReservationRecord, Byte> STATUS = createField("status", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * The column <code>vvv.reservation.value</code>.
	 */
	public final TableField<ReservationRecord, Double> VALUE = createField("value", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * The column <code>vvv.reservation.passenger_user_id</code>.
	 */
	public final TableField<ReservationRecord, Integer> PASSENGER_USER_ID = createField("passenger_user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>vvv.reservation</code> table reference
	 */
	public Reservation() {
		this("reservation", null);
	}

	/**
	 * Create an aliased <code>vvv.reservation</code> table reference
	 */
	public Reservation(String alias) {
		this(alias, RESERVATION);
	}

	private Reservation(String alias, Table<ReservationRecord> aliased) {
		this(alias, aliased, null);
	}

	private Reservation(String alias, Table<ReservationRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<ReservationRecord> getPrimaryKey() {
		return Keys.KEY_RESERVATION_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<ReservationRecord>> getKeys() {
		return Arrays.<UniqueKey<ReservationRecord>>asList(Keys.KEY_RESERVATION_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<ReservationRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<ReservationRecord, ?>>asList(Keys.FK_RESERVATION_PASSENGER1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Reservation as(String alias) {
		return new Reservation(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Reservation rename(String name) {
		return new Reservation(name, null);
	}
}
