/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.RetailOutletRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RetailOutlet extends TableImpl<RetailOutletRecord> {

	private static final long serialVersionUID = -1402076404;

	/**
	 * The reference instance of <code>vvv.retail_outlet</code>
	 */
	public static final RetailOutlet RETAIL_OUTLET = new RetailOutlet();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RetailOutletRecord> getRecordType() {
		return RetailOutletRecord.class;
	}

	/**
	 * The column <code>vvv.retail_outlet.id</code>.
	 */
	public final TableField<RetailOutletRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.retail_outlet.name</code>.
	 */
	public final TableField<RetailOutletRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

	/**
	 * The column <code>vvv.retail_outlet.cnpj</code>.
	 */
	public final TableField<RetailOutletRecord, String> CNPJ = createField("cnpj", org.jooq.impl.SQLDataType.VARCHAR.length(14), this, "");

	/**
	 * The column <code>vvv.retail_outlet.phone</code>.
	 */
	public final TableField<RetailOutletRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR.length(50), this, "");

	/**
	 * The column <code>vvv.retail_outlet.address_id</code>.
	 */
	public final TableField<RetailOutletRecord, Integer> ADDRESS_ID = createField("address_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>vvv.retail_outlet</code> table reference
	 */
	public RetailOutlet() {
		this("retail_outlet", null);
	}

	/**
	 * Create an aliased <code>vvv.retail_outlet</code> table reference
	 */
	public RetailOutlet(String alias) {
		this(alias, RETAIL_OUTLET);
	}

	private RetailOutlet(String alias, Table<RetailOutletRecord> aliased) {
		this(alias, aliased, null);
	}

	private RetailOutlet(String alias, Table<RetailOutletRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RetailOutletRecord> getPrimaryKey() {
		return Keys.KEY_RETAIL_OUTLET_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RetailOutletRecord>> getKeys() {
		return Arrays.<UniqueKey<RetailOutletRecord>>asList(Keys.KEY_RETAIL_OUTLET_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RetailOutletRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RetailOutletRecord, ?>>asList(Keys.FK_RETAIL_OUTLET_ADDRESS1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RetailOutlet as(String alias) {
		return new RetailOutlet(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RetailOutlet rename(String name) {
		return new RetailOutlet(name, null);
	}
}
