/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables;


import Rest.Model.Keys;
import Rest.Model.Vvv;
import Rest.Model.tables.records.RouteRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Route extends TableImpl<RouteRecord> {

	private static final long serialVersionUID = -1265690216;

	/**
	 * The reference instance of <code>vvv.route</code>
	 */
	public static final Route ROUTE = new Route();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RouteRecord> getRecordType() {
		return RouteRecord.class;
	}

	/**
	 * The column <code>vvv.route.id</code>.
	 */
	public final TableField<RouteRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.departure</code>.
	 */
	public final TableField<RouteRecord, Timestamp> DEPARTURE = createField("departure", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.arrival</code>.
	 */
	public final TableField<RouteRecord, Timestamp> ARRIVAL = createField("arrival", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.modal_id</code>.
	 */
	public final TableField<RouteRecord, Integer> MODAL_ID = createField("modal_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.value</code>.
	 */
	public final TableField<RouteRecord, Double> VALUE = createField("value", org.jooq.impl.SQLDataType.FLOAT.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.origin_id</code>.
	 */
	public final TableField<RouteRecord, Integer> ORIGIN_ID = createField("origin_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>vvv.route.destination_id</code>.
	 */
	public final TableField<RouteRecord, Integer> DESTINATION_ID = createField("destination_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>vvv.route</code> table reference
	 */
	public Route() {
		this("route", null);
	}

	/**
	 * Create an aliased <code>vvv.route</code> table reference
	 */
	public Route(String alias) {
		this(alias, ROUTE);
	}

	private Route(String alias, Table<RouteRecord> aliased) {
		this(alias, aliased, null);
	}

	private Route(String alias, Table<RouteRecord> aliased, Field<?>[] parameters) {
		super(alias, Vvv.VVV, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RouteRecord> getPrimaryKey() {
		return Keys.KEY_ROUTE_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RouteRecord>> getKeys() {
		return Arrays.<UniqueKey<RouteRecord>>asList(Keys.KEY_ROUTE_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<ForeignKey<RouteRecord, ?>> getReferences() {
		return Arrays.<ForeignKey<RouteRecord, ?>>asList(Keys.FK_VIAGEM_MODAL1, Keys.FK_VIAGEM_CITY1, Keys.FK_VIAGEM_CITY2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Route as(String alias) {
		return new Route(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Route rename(String name) {
		return new Route(name, null);
	}
}
