/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Carrier;
import Rest.Model.tables.records.CarrierRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CarrierDao extends DAOImpl<CarrierRecord, Rest.Model.tables.pojos.Carrier, Integer> {

	/**
	 * Create a new CarrierDao without any configuration
	 */
	public CarrierDao() {
		super(Carrier.CARRIER, Rest.Model.tables.pojos.Carrier.class);
	}

	/**
	 * Create a new CarrierDao with an attached configuration
	 */
	public CarrierDao(Configuration configuration) {
		super(Carrier.CARRIER, Rest.Model.tables.pojos.Carrier.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.Carrier object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Carrier> fetchById(Integer... values) {
		return fetch(Carrier.CARRIER.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Rest.Model.tables.pojos.Carrier fetchOneById(Integer value) {
		return fetchOne(Carrier.CARRIER.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Carrier> fetchByName(String... values) {
		return fetch(Carrier.CARRIER.NAME, values);
	}

	/**
	 * Fetch records that have <code>url IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Carrier> fetchByUrl(String... values) {
		return fetch(Carrier.CARRIER.URL, values);
	}
}
