/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.City;
import Rest.Model.tables.records.CityRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CityDao extends DAOImpl<CityRecord, Rest.Model.tables.pojos.City, Integer> {

	/**
	 * Create a new CityDao without any configuration
	 */
	public CityDao() {
		super(City.CITY, Rest.Model.tables.pojos.City.class);
	}

	/**
	 * Create a new CityDao with an attached configuration
	 */
	public CityDao(Configuration configuration) {
		super(City.CITY, Rest.Model.tables.pojos.City.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.City object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.City> fetchById(Integer... values) {
		return fetch(City.CITY.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Rest.Model.tables.pojos.City fetchOneById(Integer value) {
		return fetchOne(City.CITY.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.City> fetchByName(String... values) {
		return fetch(City.CITY.NAME, values);
	}

	/**
	 * Fetch records that have <code>latitute IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.City> fetchByLatitute(Double... values) {
		return fetch(City.CITY.LATITUTE, values);
	}

	/**
	 * Fetch records that have <code>longitude IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.City> fetchByLongitude(Double... values) {
		return fetch(City.CITY.LONGITUDE, values);
	}
}
