/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.CreditCard;
import Rest.Model.tables.records.CreditCardRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditCardDao extends DAOImpl<CreditCardRecord, Rest.Model.tables.pojos.CreditCard, Integer> {

	/**
	 * Create a new CreditCardDao without any configuration
	 */
	public CreditCardDao() {
		super(CreditCard.CREDIT_CARD, Rest.Model.tables.pojos.CreditCard.class);
	}

	/**
	 * Create a new CreditCardDao with an attached configuration
	 */
	public CreditCardDao(Configuration configuration) {
		super(CreditCard.CREDIT_CARD, Rest.Model.tables.pojos.CreditCard.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.CreditCard object) {
		return object.getUserId();
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.CreditCard> fetchByUserId(Integer... values) {
		return fetch(CreditCard.CREDIT_CARD.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public Rest.Model.tables.pojos.CreditCard fetchOneByUserId(Integer value) {
		return fetchOne(CreditCard.CREDIT_CARD.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>number IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.CreditCard> fetchByNumber(Integer... values) {
		return fetch(CreditCard.CREDIT_CARD.NUMBER, values);
	}

	/**
	 * Fetch records that have <code>holder_name IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.CreditCard> fetchByHolderName(String... values) {
		return fetch(CreditCard.CREDIT_CARD.HOLDER_NAME, values);
	}

	/**
	 * Fetch records that have <code>expire IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.CreditCard> fetchByExpire(Date... values) {
		return fetch(CreditCard.CREDIT_CARD.EXPIRE, values);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.CreditCard> fetchByAddressId(Integer... values) {
		return fetch(CreditCard.CREDIT_CARD.ADDRESS_ID, values);
	}
}
