/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Employee;
import Rest.Model.tables.records.EmployeeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EmployeeDao extends DAOImpl<EmployeeRecord, Rest.Model.tables.pojos.Employee, Integer> {

	/**
	 * Create a new EmployeeDao without any configuration
	 */
	public EmployeeDao() {
		super(Employee.EMPLOYEE, Rest.Model.tables.pojos.Employee.class);
	}

	/**
	 * Create a new EmployeeDao with an attached configuration
	 */
	public EmployeeDao(Configuration configuration) {
		super(Employee.EMPLOYEE, Rest.Model.tables.pojos.Employee.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.Employee object) {
		return object.getUserId();
	}

	/**
	 * Fetch records that have <code>user_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByUserId(Integer... values) {
		return fetch(Employee.EMPLOYEE.USER_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>user_id = value</code>
	 */
	public Rest.Model.tables.pojos.Employee fetchOneByUserId(Integer value) {
		return fetchOne(Employee.EMPLOYEE.USER_ID, value);
	}

	/**
	 * Fetch records that have <code>cpf IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByCpf(String... values) {
		return fetch(Employee.EMPLOYEE.CPF, values);
	}

	/**
	 * Fetch a unique record that has <code>cpf = value</code>
	 */
	public Rest.Model.tables.pojos.Employee fetchOneByCpf(String value) {
		return fetchOne(Employee.EMPLOYEE.CPF, value);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByPhone(String... values) {
		return fetch(Employee.EMPLOYEE.PHONE, values);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByAddressId(Integer... values) {
		return fetch(Employee.EMPLOYEE.ADDRESS_ID, values);
	}

	/**
	 * Fetch a unique record that has <code>address_id = value</code>
	 */
	public Rest.Model.tables.pojos.Employee fetchOneByAddressId(Integer value) {
		return fetchOne(Employee.EMPLOYEE.ADDRESS_ID, value);
	}

	/**
	 * Fetch records that have <code>post IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByPost(Byte... values) {
		return fetch(Employee.EMPLOYEE.POST, values);
	}

	/**
	 * Fetch records that have <code>work_days IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Employee> fetchByWorkDays(byte[]... values) {
		return fetch(Employee.EMPLOYEE.WORK_DAYS, values);
	}
}
