/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Itinerary;
import Rest.Model.tables.records.ItineraryRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItineraryDao extends DAOImpl<ItineraryRecord, Rest.Model.tables.pojos.Itinerary, Record2<Integer, Integer>> {

	/**
	 * Create a new ItineraryDao without any configuration
	 */
	public ItineraryDao() {
		super(Itinerary.ITINERARY, Rest.Model.tables.pojos.Itinerary.class);
	}

	/**
	 * Create a new ItineraryDao with an attached configuration
	 */
	public ItineraryDao(Configuration configuration) {
		super(Itinerary.ITINERARY, Rest.Model.tables.pojos.Itinerary.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(Rest.Model.tables.pojos.Itinerary object) {
		return compositeKeyRecord(object.getReservationId(), object.getViagemId());
	}

	/**
	 * Fetch records that have <code>reservation_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Itinerary> fetchByReservationId(Integer... values) {
		return fetch(Itinerary.ITINERARY.RESERVATION_ID, values);
	}

	/**
	 * Fetch records that have <code>viagem_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Itinerary> fetchByViagemId(Integer... values) {
		return fetch(Itinerary.ITINERARY.VIAGEM_ID, values);
	}
}
