/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Modal;
import Rest.Model.tables.records.ModalRecord;

import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModalDao extends DAOImpl<ModalRecord, Rest.Model.tables.pojos.Modal, Integer> {

	/**
	 * Create a new ModalDao without any configuration
	 */
	public ModalDao() {
		super(Modal.MODAL, Rest.Model.tables.pojos.Modal.class);
	}

	/**
	 * Create a new ModalDao with an attached configuration
	 */
	public ModalDao(Configuration configuration) {
		super(Modal.MODAL, Rest.Model.tables.pojos.Modal.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.Modal object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchById(Integer... values) {
		return fetch(Modal.MODAL.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Rest.Model.tables.pojos.Modal fetchOneById(Integer value) {
		return fetchOne(Modal.MODAL.ID, value);
	}

	/**
	 * Fetch records that have <code>type IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByType(Integer... values) {
		return fetch(Modal.MODAL.TYPE, values);
	}

	/**
	 * Fetch records that have <code>capacity IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByCapacity(Integer... values) {
		return fetch(Modal.MODAL.CAPACITY, values);
	}

	/**
	 * Fetch records that have <code>model IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByModel(String... values) {
		return fetch(Modal.MODAL.MODEL, values);
	}

	/**
	 * Fetch records that have <code>manufacture IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByManufacture(Date... values) {
		return fetch(Modal.MODAL.MANUFACTURE, values);
	}

	/**
	 * Fetch records that have <code>maintenance_start IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByMaintenanceStart(Date... values) {
		return fetch(Modal.MODAL.MAINTENANCE_START, values);
	}

	/**
	 * Fetch records that have <code>maintenance_end IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByMaintenanceEnd(Date... values) {
		return fetch(Modal.MODAL.MAINTENANCE_END, values);
	}

	/**
	 * Fetch records that have <code>carriers_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Modal> fetchByCarriersId(Integer... values) {
		return fetch(Modal.MODAL.CARRIERS_ID, values);
	}
}
