/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.RetailOutlet;
import Rest.Model.tables.records.RetailOutletRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RetailOutletDao extends DAOImpl<RetailOutletRecord, Rest.Model.tables.pojos.RetailOutlet, Integer> {

	/**
	 * Create a new RetailOutletDao without any configuration
	 */
	public RetailOutletDao() {
		super(RetailOutlet.RETAIL_OUTLET, Rest.Model.tables.pojos.RetailOutlet.class);
	}

	/**
	 * Create a new RetailOutletDao with an attached configuration
	 */
	public RetailOutletDao(Configuration configuration) {
		super(RetailOutlet.RETAIL_OUTLET, Rest.Model.tables.pojos.RetailOutlet.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.RetailOutlet object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.RetailOutlet> fetchById(Integer... values) {
		return fetch(RetailOutlet.RETAIL_OUTLET.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Rest.Model.tables.pojos.RetailOutlet fetchOneById(Integer value) {
		return fetchOne(RetailOutlet.RETAIL_OUTLET.ID, value);
	}

	/**
	 * Fetch records that have <code>name IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.RetailOutlet> fetchByName(String... values) {
		return fetch(RetailOutlet.RETAIL_OUTLET.NAME, values);
	}

	/**
	 * Fetch records that have <code>cnpj IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.RetailOutlet> fetchByCnpj(String... values) {
		return fetch(RetailOutlet.RETAIL_OUTLET.CNPJ, values);
	}

	/**
	 * Fetch records that have <code>phone IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.RetailOutlet> fetchByPhone(String... values) {
		return fetch(RetailOutlet.RETAIL_OUTLET.PHONE, values);
	}

	/**
	 * Fetch records that have <code>address_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.RetailOutlet> fetchByAddressId(Integer... values) {
		return fetch(RetailOutlet.RETAIL_OUTLET.ADDRESS_ID, values);
	}
}
