/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Route;
import Rest.Model.tables.records.RouteRecord;

import java.sql.Timestamp;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RouteDao extends DAOImpl<RouteRecord, Rest.Model.tables.pojos.Route, Integer> {

	/**
	 * Create a new RouteDao without any configuration
	 */
	public RouteDao() {
		super(Route.ROUTE, Rest.Model.tables.pojos.Route.class);
	}

	/**
	 * Create a new RouteDao with an attached configuration
	 */
	public RouteDao(Configuration configuration) {
		super(Route.ROUTE, Rest.Model.tables.pojos.Route.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Integer getId(Rest.Model.tables.pojos.Route object) {
		return object.getId();
	}

	/**
	 * Fetch records that have <code>id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchById(Integer... values) {
		return fetch(Route.ROUTE.ID, values);
	}

	/**
	 * Fetch a unique record that has <code>id = value</code>
	 */
	public Rest.Model.tables.pojos.Route fetchOneById(Integer value) {
		return fetchOne(Route.ROUTE.ID, value);
	}

	/**
	 * Fetch records that have <code>departure IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByDeparture(Timestamp... values) {
		return fetch(Route.ROUTE.DEPARTURE, values);
	}

	/**
	 * Fetch records that have <code>arrival IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByArrival(Timestamp... values) {
		return fetch(Route.ROUTE.ARRIVAL, values);
	}

	/**
	 * Fetch records that have <code>modal_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByModalId(Integer... values) {
		return fetch(Route.ROUTE.MODAL_ID, values);
	}

	/**
	 * Fetch records that have <code>value IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByValue(Double... values) {
		return fetch(Route.ROUTE.VALUE, values);
	}

	/**
	 * Fetch records that have <code>origin_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByOriginId(Integer... values) {
		return fetch(Route.ROUTE.ORIGIN_ID, values);
	}

	/**
	 * Fetch records that have <code>destination_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Route> fetchByDestinationId(Integer... values) {
		return fetch(Route.ROUTE.DESTINATION_ID, values);
	}
}
