/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.daos;


import Rest.Model.tables.Staff;
import Rest.Model.tables.records.StaffRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StaffDao extends DAOImpl<StaffRecord, Rest.Model.tables.pojos.Staff, Record2<Integer, Integer>> {

	/**
	 * Create a new StaffDao without any configuration
	 */
	public StaffDao() {
		super(Staff.STAFF, Rest.Model.tables.pojos.Staff.class);
	}

	/**
	 * Create a new StaffDao with an attached configuration
	 */
	public StaffDao(Configuration configuration) {
		super(Staff.STAFF, Rest.Model.tables.pojos.Staff.class, configuration);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected Record2<Integer, Integer> getId(Rest.Model.tables.pojos.Staff object) {
		return compositeKeyRecord(object.getRetailOutletId(), object.getEmployeeUserId());
	}

	/**
	 * Fetch records that have <code>retail_outlet_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Staff> fetchByRetailOutletId(Integer... values) {
		return fetch(Staff.STAFF.RETAIL_OUTLET_ID, values);
	}

	/**
	 * Fetch records that have <code>employee_user_id IN (values)</code>
	 */
	public List<Rest.Model.tables.pojos.Staff> fetchByEmployeeUserId(Integer... values) {
		return fetch(Staff.STAFF.EMPLOYEE_USER_ID, values);
	}
}
