/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import com.fasterxml.jackson.annotation.JsonIgnore;

import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * User Address
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "Address", schema = "vvv")
public class Address implements Serializable {

	private static final long serialVersionUID = -2051689476;

	@JsonIgnore
	private Integer id;

	@JsonIgnore
	private Integer userId;
	private String  street;
	private Integer number;
	private String  complement;
	private String  city;
	private String  state;

	public Address() {}

	public Address(Address value) {
		this.id = value.id;
		this.userId = value.userId;
		this.street = value.street;
		this.number = value.number;
		this.complement = value.complement;
		this.city = value.city;
		this.state = value.state;
	}

	public Address(
		Integer id,
		Integer userId,
		String  street,
		Integer number,
		String  complement,
		String  city,
		String  state
	) {
		this.id = id;
		this.userId = userId;
		this.street = street;
		this.number = number;
		this.complement = complement;
		this.city = city;
		this.state = state;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "user_id", precision = 10)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "street", nullable = false, length = 255)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "number", precision = 10)
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "complement", length = 255)
	public String getComplement() {
		return this.complement;
	}

	public void setComplement(String complement) {
		this.complement = complement;
	}

	@Column(name = "city", nullable = false, length = 255)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 255)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Address (");

		sb.append(id);
		sb.append(", ").append(userId);
		sb.append(", ").append(street);
		sb.append(", ").append(number);
		sb.append(", ").append(complement);
		sb.append(", ").append(city);
		sb.append(", ").append(state);

		sb.append(")");
		return sb.toString();
	}
}
