/**
 * This class is generated by jOOQ
 */
package Rest.Model;


import Rest.Model.tables.Address;
import Rest.Model.tables.CreditCard;
import Rest.Model.tables.User;
import Rest.Model.tables.records.AddressRecord;
import Rest.Model.tables.records.CreditCardRecord;
import Rest.Model.tables.records.UserRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;


/**
 * A class modelling foreign key relationships between tables of the <code>vvv</code> 
 * schema
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<AddressRecord, Integer> IDENTITY_ADDRESS = Identities0.IDENTITY_ADDRESS;
	public static final Identity<UserRecord, Integer> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = UniqueKeys0.KEY_ADDRESS_PRIMARY;
	public static final UniqueKey<CreditCardRecord> KEY_CREDIT_CARD_PRIMARY = UniqueKeys0.KEY_CREDIT_CARD_PRIMARY;
	public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final ForeignKey<AddressRecord, UserRecord> ADDRESS_IBFK_1 = ForeignKeys0.ADDRESS_IBFK_1;
	public static final ForeignKey<CreditCardRecord, UserRecord> CREDIT_CARD_IBFK_1 = ForeignKeys0.CREDIT_CARD_IBFK_1;
	public static final ForeignKey<CreditCardRecord, AddressRecord> CREDIT_CARD_IBFK_2 = ForeignKeys0.CREDIT_CARD_IBFK_2;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<AddressRecord, Integer> IDENTITY_ADDRESS = createIdentity(Address.ADDRESS, Address.ADDRESS.ID);
		public static Identity<UserRecord, Integer> IDENTITY_USER = createIdentity(User.USER, User.USER.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AddressRecord> KEY_ADDRESS_PRIMARY = createUniqueKey(Address.ADDRESS, Address.ADDRESS.ID);
		public static final UniqueKey<CreditCardRecord> KEY_CREDIT_CARD_PRIMARY = createUniqueKey(CreditCard.CREDIT_CARD, CreditCard.CREDIT_CARD.ID);
		public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = createUniqueKey(User.USER, User.USER.ID);
	}

	private static class ForeignKeys0 extends AbstractKeys {
		public static final ForeignKey<AddressRecord, UserRecord> ADDRESS_IBFK_1 = createForeignKey(Rest.Model.Keys.KEY_USER_PRIMARY, Address.ADDRESS, Address.ADDRESS.USER_ID);
		public static final ForeignKey<CreditCardRecord, UserRecord> CREDIT_CARD_IBFK_1 = createForeignKey(Rest.Model.Keys.KEY_USER_PRIMARY, CreditCard.CREDIT_CARD, CreditCard.CREDIT_CARD.ID);
		public static final ForeignKey<CreditCardRecord, AddressRecord> CREDIT_CARD_IBFK_2 = createForeignKey(Rest.Model.Keys.KEY_ADDRESS_PRIMARY, CreditCard.CREDIT_CARD, CreditCard.CREDIT_CARD.FACTURE_ADDRESS_ID);
	}
}
