/**
 * This class is generated by jOOQ
 */
package Rest.Model;


import Rest.Model.tables.Address;
import Rest.Model.tables.CreditCard;
import Rest.Model.tables.User;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in vvv
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table vvv.address
	 */
	public static final Address ADDRESS = Rest.Model.tables.Address.ADDRESS;

	/**
	 * The table vvv.credit_card
	 */
	public static final CreditCard CREDIT_CARD = Rest.Model.tables.CreditCard.CREDIT_CARD;

	/**
	 * The table vvv.user
	 */
	public static final User USER = Rest.Model.tables.User.USER;
}
