/**
 * This class is generated by jOOQ
 */
package Rest.Model;


import Rest.Model.tables.Address;
import Rest.Model.tables.CreditCard;
import Rest.Model.tables.User;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Vvv extends SchemaImpl {

	private static final long serialVersionUID = 938796493;

	/**
	 * The reference instance of <code>vvv</code>
	 */
	public static final Vvv VVV = new Vvv();

	/**
	 * No further instances allowed
	 */
	private Vvv() {
		super("vvv");
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(
			Address.ADDRESS,
			CreditCard.CREDIT_CARD,
			User.USER);
	}
}
