/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "address", schema = "vvv")
public class Address implements Serializable {

	private static final long serialVersionUID = 805632527;

	private Integer id;
	private String  street;
	private Integer number;
	private String  city;
	private String  state;
	private String  country;

	public Address() {}

	public Address(Address value) {
		this.id = value.id;
		this.street = value.street;
		this.number = value.number;
		this.city = value.city;
		this.state = value.state;
		this.country = value.country;
	}

	public Address(
		Integer id,
		String  street,
		Integer number,
		String  city,
		String  state,
		String  country
	) {
		this.id = id;
		this.street = street;
		this.number = number;
		this.city = city;
		this.state = state;
		this.country = country;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "street", nullable = false, length = 255)
	public String getStreet() {
		return this.street;
	}

	public void setStreet(String street) {
		this.street = street;
	}

	@Column(name = "number", precision = 10)
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@Column(name = "city", nullable = false, length = 255)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 255)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 255)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Address (");

		sb.append(id);
		sb.append(", ").append(street);
		sb.append(", ").append(number);
		sb.append(", ").append(city);
		sb.append(", ").append(state);
		sb.append(", ").append(country);

		sb.append(")");
		return sb.toString();
	}
}
