/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "carrier", schema = "vvv")
public class Carrier implements Serializable {

	private static final long serialVersionUID = -2127167654;

	private Integer id;
	private String  name;
	private String  url;

	public Carrier() {}

	public Carrier(Carrier value) {
		this.id = value.id;
		this.name = value.name;
		this.url = value.url;
	}

	public Carrier(
		Integer id,
		String  name,
		String  url
	) {
		this.id = id;
		this.name = name;
		this.url = url;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "url", nullable = false, length = 65535)
	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Carrier (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(url);

		sb.append(")");
		return sb.toString();
	}
}
