/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "employee", schema = "vvv")
public class Employee implements Serializable {

	private static final long serialVersionUID = 437636707;

	private Integer userId;
	private String  cpf;
	private String  phone;
	private Integer addressId;
	private Byte    post;
	private byte[]  workDays;

	public Employee() {}

	public Employee(Employee value) {
		this.userId = value.userId;
		this.cpf = value.cpf;
		this.phone = value.phone;
		this.addressId = value.addressId;
		this.post = value.post;
		this.workDays = value.workDays;
	}

	public Employee(
		Integer userId,
		String  cpf,
		String  phone,
		Integer addressId,
		Byte    post,
		byte[]  workDays
	) {
		this.userId = userId;
		this.cpf = cpf;
		this.phone = phone;
		this.addressId = addressId;
		this.post = post;
		this.workDays = workDays;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, precision = 10)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "cpf", unique = true, nullable = false, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address_id", unique = true, nullable = false, precision = 10)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "post", nullable = false, precision = 3)
	public Byte getPost() {
		return this.post;
	}

	public void setPost(Byte post) {
		this.post = post;
	}

	@Column(name = "work_days", length = 7)
	public byte[] getWorkDays() {
		return this.workDays;
	}

	public void setWorkDays(byte[] workDays) {
		this.workDays = workDays;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Employee (");

		sb.append(userId);
		sb.append(", ").append(cpf);
		sb.append(", ").append(phone);
		sb.append(", ").append(addressId);
		sb.append(", ").append(post);
		sb.append(", ").append("[binary...]");

		sb.append(")");
		return sb.toString();
	}
}
