/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "itinerary", schema = "vvv", uniqueConstraints = {
	@UniqueConstraint(columnNames = {"reservation_id", "viagem_id"})
})
public class Itinerary implements Serializable {

	private static final long serialVersionUID = 1679005112;

	private Integer reservationId;
	private Integer viagemId;

	public Itinerary() {}

	public Itinerary(Itinerary value) {
		this.reservationId = value.reservationId;
		this.viagemId = value.viagemId;
	}

	public Itinerary(
		Integer reservationId,
		Integer viagemId
	) {
		this.reservationId = reservationId;
		this.viagemId = viagemId;
	}

	@Column(name = "reservation_id", nullable = false, precision = 10)
	public Integer getReservationId() {
		return this.reservationId;
	}

	public void setReservationId(Integer reservationId) {
		this.reservationId = reservationId;
	}

	@Column(name = "viagem_id", nullable = false, precision = 10)
	public Integer getViagemId() {
		return this.viagemId;
	}

	public void setViagemId(Integer viagemId) {
		this.viagemId = viagemId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Itinerary (");

		sb.append(reservationId);
		sb.append(", ").append(viagemId);

		sb.append(")");
		return sb.toString();
	}
}
