/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "oAuth", schema = "vvv")
public class Oauth implements Serializable {

	private static final long serialVersionUID = 870600466;

	private byte[]    token;
	private Timestamp lastLoginAt;
	private Integer   userId;

	public Oauth() {}

	public Oauth(Oauth value) {
		this.token = value.token;
		this.lastLoginAt = value.lastLoginAt;
		this.userId = value.userId;
	}

	public Oauth(
		byte[]    token,
		Timestamp lastLoginAt,
		Integer   userId
	) {
		this.token = token;
		this.lastLoginAt = lastLoginAt;
		this.userId = userId;
	}

	@Column(name = "token", nullable = false, length = 96)
	public byte[] getToken() {
		return this.token;
	}

	public void setToken(byte[] token) {
		this.token = token;
	}

	@Column(name = "last_login_at", nullable = false)
	public Timestamp getLastLoginAt() {
		return this.lastLoginAt;
	}

	public void setLastLoginAt(Timestamp lastLoginAt) {
		this.lastLoginAt = lastLoginAt;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, precision = 10)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Oauth (");

		sb.append("[binary...]");
		sb.append(", ").append(lastLoginAt);
		sb.append(", ").append(userId);

		sb.append(")");
		return sb.toString();
	}
}
