/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "passenger", schema = "vvv")
public class Passenger extends User implements Serializable {

	private static final long serialVersionUID = 1082403961;

	private Integer userId;
	private String  cpf;
	private String  phone;
	private String  occupation;
	private Integer addressId;

	public Passenger() {}

	public Passenger(Passenger value) {
		this.userId = value.userId;
		this.cpf = value.cpf;
		this.phone = value.phone;
		this.occupation = value.occupation;
		this.addressId = value.addressId;
	}

	public Passenger(
		Integer userId,
		String  cpf,
		String  phone,
		String  occupation,
		Integer addressId
	) {
		this.userId = userId;
		this.cpf = cpf;
		this.phone = phone;
		this.occupation = occupation;
		this.addressId = addressId;
	}

	@Id
	@Column(name = "user_id", unique = true, nullable = false, precision = 10)
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Column(name = "cpf", unique = true, length = 11)
	public String getCpf() {
		return this.cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	@Column(name = "phone", nullable = false, length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "occupation", nullable = false, length = 255)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "address_id", unique = true, nullable = false, precision = 10)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Passenger (");

		sb.append(userId);
		sb.append(", ").append(cpf);
		sb.append(", ").append(phone);
		sb.append(", ").append(occupation);
		sb.append(", ").append(addressId);

		sb.append(")");
		return sb.toString();
	}
}
