/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "reservation", schema = "vvv")
public class Reservation implements Serializable {

	private static final long serialVersionUID = 1989305128;

	private Integer   id;
	private Timestamp date;
	private Byte      status;
	private Double    value;
	private Integer   passengerUserId;

	public Reservation() {}

	public Reservation(Reservation value) {
		this.id = value.id;
		this.date = value.date;
		this.status = value.status;
		this.value = value.value;
		this.passengerUserId = value.passengerUserId;
	}

	public Reservation(
		Integer   id,
		Timestamp date,
		Byte      status,
		Double    value,
		Integer   passengerUserId
	) {
		this.id = id;
		this.date = date;
		this.status = status;
		this.value = value;
		this.passengerUserId = passengerUserId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "date", nullable = false)
	public Timestamp getDate() {
		return this.date;
	}

	public void setDate(Timestamp date) {
		this.date = date;
	}

	@Column(name = "status", nullable = false, precision = 3)
	public Byte getStatus() {
		return this.status;
	}

	public void setStatus(Byte status) {
		this.status = status;
	}

	@Column(name = "value", nullable = false, precision = 12)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Column(name = "passenger_user_id", nullable = false, precision = 10)
	public Integer getPassengerUserId() {
		return this.passengerUserId;
	}

	public void setPassengerUserId(Integer passengerUserId) {
		this.passengerUserId = passengerUserId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Reservation (");

		sb.append(id);
		sb.append(", ").append(date);
		sb.append(", ").append(status);
		sb.append(", ").append(value);
		sb.append(", ").append(passengerUserId);

		sb.append(")");
		return sb.toString();
	}
}
