/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "retail_outlet", schema = "vvv")
public class RetailOutlet implements Serializable {

	private static final long serialVersionUID = 1187760525;

	private Integer id;
	private String  name;
	private String  cnpj;
	private String  phone;
	private Integer addressId;

	public RetailOutlet() {}

	public RetailOutlet(RetailOutlet value) {
		this.id = value.id;
		this.name = value.name;
		this.cnpj = value.cnpj;
		this.phone = value.phone;
		this.addressId = value.addressId;
	}

	public RetailOutlet(
		Integer id,
		String  name,
		String  cnpj,
		String  phone,
		Integer addressId
	) {
		this.id = id;
		this.name = name;
		this.cnpj = cnpj;
		this.phone = phone;
		this.addressId = addressId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 255)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cnpj", length = 14)
	public String getCnpj() {
		return this.cnpj;
	}

	public void setCnpj(String cnpj) {
		this.cnpj = cnpj;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "address_id", nullable = false, precision = 10)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("RetailOutlet (");

		sb.append(id);
		sb.append(", ").append(name);
		sb.append(", ").append(cnpj);
		sb.append(", ").append(phone);
		sb.append(", ").append(addressId);

		sb.append(")");
		return sb.toString();
	}
}
