/**
 * This class is generated by jOOQ
 */
package Rest.Model.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.1"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "route", schema = "vvv")
public class Route implements Serializable {

	private static final long serialVersionUID = -128368138;

	private Integer   id;
	private Timestamp departure;
	private Timestamp arrival;
	private Integer   modalId;
	private Double    value;
	private Integer   originId;
	private Integer   destinationId;

	public Route() {}

	public Route(Route value) {
		this.id = value.id;
		this.departure = value.departure;
		this.arrival = value.arrival;
		this.modalId = value.modalId;
		this.value = value.value;
		this.originId = value.originId;
		this.destinationId = value.destinationId;
	}

	public Route(
		Integer   id,
		Timestamp departure,
		Timestamp arrival,
		Integer   modalId,
		Double    value,
		Integer   originId,
		Integer   destinationId
	) {
		this.id = id;
		this.departure = departure;
		this.arrival = arrival;
		this.modalId = modalId;
		this.value = value;
		this.originId = originId;
		this.destinationId = destinationId;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false, precision = 10)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "departure", nullable = false)
	public Timestamp getDeparture() {
		return this.departure;
	}

	public void setDeparture(Timestamp departure) {
		this.departure = departure;
	}

	@Column(name = "arrival", nullable = false)
	public Timestamp getArrival() {
		return this.arrival;
	}

	public void setArrival(Timestamp arrival) {
		this.arrival = arrival;
	}

	@Column(name = "modal_id", nullable = false, precision = 10)
	public Integer getModalId() {
		return this.modalId;
	}

	public void setModalId(Integer modalId) {
		this.modalId = modalId;
	}

	@Column(name = "value", nullable = false, precision = 12)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Column(name = "origin_id", nullable = false, precision = 10)
	public Integer getOriginId() {
		return this.originId;
	}

	public void setOriginId(Integer originId) {
		this.originId = originId;
	}

	@Column(name = "destination_id", nullable = false, precision = 10)
	public Integer getDestinationId() {
		return this.destinationId;
	}

	public void setDestinationId(Integer destinationId) {
		this.destinationId = destinationId;
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder("Route (");

		sb.append(id);
		sb.append(", ").append(departure);
		sb.append(", ").append(arrival);
		sb.append(", ").append(modalId);
		sb.append(", ").append(value);
		sb.append(", ").append(originId);
		sb.append(", ").append(destinationId);

		sb.append(")");
		return sb.toString();
	}
}
